### PR TITLE
update nyx bookkeeping

### PR DESCRIPTION
**Pull request by jchavesmontero**

### CODE REVIEW

**Review by andreufont — COMMENTED** [review]
@jchavesmontero - at which point in the code do you reject now the simulation 14?

**Comment by andreufont** [comment]
@lauracabayol - please take care of the review, since I can not test it now

**Comment by jchavesmontero** [comment]
> @jchavesmontero - at which point in the code do you reject now the simulation 14?

I haven't changed that, still in line https://github.com/igmhub/LaCE/blob/d4ddde7b0a3f00bb79a33ee4d98f1a048c87f13c/src/lace/archive/nyx_archive.py#L277

**Comment by andreufont** [comment]
> > @jchavesmontero - at which point in the code do you reject now the simulation 14?
> 
> I haven't changed that, still in line
> 
> https://github.com/igmhub/LaCE/blob/d4ddde7b0a3f00bb79a33ee4d98f1a048c87f13c/src/lace/archive/nyx_archive.py#L277

That's fine for now, thanks!

**Review by lauracabayol — APPROVED** [review]
I have run it again after the merging of pip installable PR and it load the new nyx models

**Pull request merged**
