### PR TITLE
scripts to test the emulators and archives

### PR DESCRIPTION
**Pull request by lauracabayol**
I have added a directory with four scripts to test the archives and emulators.
This is the first step for the automated testing. 
Please, test if you can run them.

### CODE REVIEW

**Review by jchavesmontero — APPROVED** [review]
Everything works perfectly! I only have a minor suggestion. The GP emulator returns: 
Training GP on 330 points
GPs optimised in 0.29 seconds
while the NN emulator does not return anything. Could we either include this info for the NN emulator or remove it from the first? I suggest this for consistency.

**Comment by lauracabayol** [comment]
Now yes! Ok, let me fix this!

**Comment by lauracabayol** [comment]
since these changes are in the nn_emulator.py (not in the scripts) and I have the other PR of the randomness open, I wpuld add the prints there instead of in this PR. Is this ok for you?

**Comment by lauracabayol** [comment]
@andreufont , do you want to test this or I can merge?

**Pull request merged**
