### PR TITLE
Nyx cosmo

### PR DESCRIPTION
**Pull request by jchavesmontero**
Moving from lambda_P to k_F in the nyx emulator, fixing some issues in LaCE notebooks

### CODE REVIEW

**Comment by lauracabayol** [comment]
I'm finding this when running the bookkeeping tutorial. 
Screenshot 2023-11-02 at 23 14 04

Do you know why this happens?

**Comment by jchavesmontero** [comment]
Yes, there is not more lambda_P, let me fix it

**Comment by jchavesmontero** [comment]
@lauracabayol @andreufont I have just checked that the notebooks are up and running. I am ready to merge the branch

**Review by andreufont — COMMENTED** [review]
I checked that the notebooks run in the new branch, also on my laptop. I have not checked cup1d, but I understand that you have checked that as well @jchavesmontero ?

**Comment by jchavesmontero** [comment]
@andreufont  Yes, I am using cup1d and everything looks fine. I am working on a bookkeeper for tests now

**Comment by andreufont** [comment]
In this case I'm also happy to merge!

**Review by andreufont — APPROVED** [review]

**Pull request merged**
